#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: ac9-pv-claim
#  labels:
#    app: ac9
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac9
  labels:
    app: ac9
spec:
#  securityContext:
#    seccompProfile: 
#      type: RuntimeDefault 
#    runAsNonRoot: true 
  replicas: 1
  selector:
    matchLabels:
      app: ac9
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: ac9
    spec:
      containers:
      - image: quay.io/danclark/ac9:latest
        imagePullPolicy: Always
        name: ac9
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 12312
          name: syslog-port
#        volumeMounts:
#        - name: ac9-persistent-storage
#          mountPath: /opt/data
#      volumes:
#      - name: ac9-persistent-storage
#        persistentVolumeClaim:
#          claimName: ac9-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: syslog
  labels:
    app: ac9
spec:
  ports:
    - port: 12312
      name: syslog-port
      protocol: UDP
      targetPort: 12312
  selector:
    app: ac9
