apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: myforwarder
  namespace: openshift-logging 
spec:
  outputs:
   - name: rsyslog-east
     type: syslog 
     url: 'udp://syslog:12312'
#     syslog: 
#       facility: local0
#       rfc: RFC3164
#       payloadKey: message
#       severity: informational
#     secret: 
#        name: syslog-secret
  serviceAccountName: rsyslog
  pipelines:
   - name: syslog-east 
     detectMultilineErrors: true
     inputRefs: 
     - audit
     outputRefs: 
     - rsyslog-east
     labels:
       syslog: "east"
